import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../data/providers/schedule_provider.dart';
import '../data/models/schedule_event_model.dart';
import '../../tasks/data/providers/tasks_provider.dart';
import 'create_edit_schedule_screen.dart';

class _ScheduleDisplayItem {
  final String id;
  final String title;
  final String? description;
  final DateTime startTime;
  final DateTime? endTime;
  final String type;
  final bool isTask;
  final bool hasAssignees;
  final String? projectName;
  final String? taskStatus;

  _ScheduleDisplayItem({
    required this.id,
    required this.title,
    this.description,
    required this.startTime,
    this.endTime,
    required this.type,
    this.isTask = false,
    this.hasAssignees = false,
    this.projectName,
    this.taskStatus,
  });

  factory _ScheduleDisplayItem.fromEvent(ScheduleEventModel event) {
    final linkedTitle = event.linkedTask?['title']?.toString();
    final displayTitle = linkedTitle != null
        ? 'Task: $linkedTitle'
        : event.title;

    return _ScheduleDisplayItem(
      id: event.id,
      title: displayTitle,
      description: event.description,
      startTime: event.startTime,
      endTime: event.endTime,
      type: event.linkedTaskId != null ? 'DEADLINE' : event.type,
      isTask: event.linkedTaskId != null || event.autoGenerated,
      projectName: event.project?['name']?.toString(),
      hasAssignees: event.linkedTaskId != null,
      taskStatus: event.linkedTask?['status']?.toString(),
    );
  }

  factory _ScheduleDisplayItem.fromTask(Map<String, dynamic> task) {
    final when = _ScheduleDisplayItem._taskDateTime(task);
    return _ScheduleDisplayItem(
      id: 'task-${task['id']}',
      title: 'Task: ${task['title'] ?? 'Untitled'}',
      description: task['description']?.toString(),
      startTime: when,
      endTime: when,
      type: 'DEADLINE',
      isTask: true,
      hasAssignees: (task['assignees'] as List?)?.isNotEmpty ?? false,
      projectName: (task['project'] as Map?)?['name']?.toString(),
      taskStatus: task['status']?.toString(),
    );
  }

  static DateTime _taskDateTime(Map<String, dynamic> task) {
    final dueStr = task['dueDate']?.toString();
    if (dueStr != null) {
      final due = DateTime.tryParse(dueStr);
      if (due != null) return due.toLocal();
    }
    final createdStr = task['createdAt']?.toString();
    if (createdStr != null) {
      final created = DateTime.tryParse(createdStr);
      if (created != null) return created.toLocal();
    }
    return DateTime.now();
  }

  static DateTime taskScheduleDate(Map<String, dynamic> task) {
    final dueStr = task['dueDate']?.toString();
    if (dueStr != null) {
      final due = DateTime.tryParse(dueStr)?.toLocal();
      if (due != null) return due;
    }
    final createdStr = task['createdAt']?.toString();
    if (createdStr != null) {
      final created = DateTime.tryParse(createdStr)?.toLocal();
      if (created != null) return created;
    }
    return DateTime.now();
  }

  String get timeRange {
    final start = DateFormat('h:mm a').format(startTime);
    if (endTime != null &&
        endTime!.hour != startTime.hour &&
        endTime!.minute != startTime.minute) {
      return '$start - ${DateFormat('h:mm a').format(endTime!)}';
    }
    return start;
  }
}

class ScheduleScreen extends ConsumerStatefulWidget {
  const ScheduleScreen({super.key});

  @override
  ConsumerState<ScheduleScreen> createState() => _ScheduleScreenState();
}

class _ScheduleScreenState extends ConsumerState<ScheduleScreen> {
  DateTime _selectedDate = DateTime.now();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _refresh());
  }

  Future<void> _refresh() async {
    await Future.wait([
      ref.read(scheduleProvider.notifier).fetchEvents(),
      ref.read(tasksProvider.notifier).fetchTasks(),
    ]);
  }

  bool _isSameDay(DateTime a, DateTime b) {
    return a.year == b.year && a.month == b.month && a.day == b.day;
  }

  List<_ScheduleDisplayItem> _itemsForDate(
    List<ScheduleEventModel> events,
    List<Map<String, dynamic>> tasks,
    DateTime date,
  ) {
    final linkedTaskIds = events
        .where((e) => e.linkedTaskId != null)
        .map((e) => e.linkedTaskId!)
        .toSet();

    final items = <_ScheduleDisplayItem>[];

    for (final event in events) {
      if (_isSameDay(event.startTime, date)) {
        items.add(_ScheduleDisplayItem.fromEvent(event));
      }
    }

    for (final task in tasks) {
      final taskDate = _ScheduleDisplayItem.taskScheduleDate(task);
      if (!_isSameDay(taskDate, date)) continue;
      if (linkedTaskIds.contains(task['id']?.toString())) continue;
      items.add(_ScheduleDisplayItem.fromTask(task));
    }

    items.sort((a, b) => a.startTime.compareTo(b.startTime));
    return items;
  }

  IconData _iconForType(String type) {
    switch (type) {
      case 'CALL':
        return Icons.phone;
      case 'DEADLINE':
        return Icons.flag;
      case 'DELIVERABLE':
        return Icons.inventory_2;
      case 'MEETING':
      default:
        return Icons.video_call;
    }
  }

  Color _tintForType(String type) {
    switch (type) {
      case 'CALL':
        return const Color(0xFFE8F5E9);
      case 'DEADLINE':
        return const Color(0xFFFBE9E7);
      case 'DELIVERABLE':
        return const Color(0xFFFFF3E0);
      case 'MEETING':
      default:
        return const Color(0xFFE3F2FD);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheduleAsync = ref.watch(scheduleProvider);
    final tasksAsync = ref.watch(tasksProvider);

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        title: const Text('Schedule'),
        actions: [
          IconButton(
            icon: const Icon(Icons.add),
            onPressed: () async {
              await Navigator.of(context).push(
                MaterialPageRoute(
                    builder: (_) => const CreateEditScheduleScreen()),
              );
              _refresh();
            },
          ),
        ],
      ),
      body: scheduleAsync.when(
        loading: () => tasksAsync.isLoading
            ? const Center(child: CircularProgressIndicator())
            : _buildScheduleBody(theme, [], tasksAsync.value ?? []),
        error: (err, _) => Center(child: Text('Error: $err')),
        data: (events) {
          if (tasksAsync.isLoading && !tasksAsync.hasValue) {
            return _buildScheduleBody(theme, events, []);
          }
          return tasksAsync.when(
            loading: () => _buildScheduleBody(theme, events, []),
            error: (_, __) => _buildScheduleBody(theme, events, []),
            data: (tasks) => _buildScheduleBody(theme, events, tasks),
          );
        },
      ),
    );
  }

  Widget _buildScheduleBody(
    ThemeData theme,
    List<ScheduleEventModel> events,
    List<Map<String, dynamic>> tasks,
  ) {
    final dayItems = _itemsForDate(events, tasks, _selectedDate);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildScrollableCalendar(theme, events, tasks),
        Divider(
            height: 1, color: theme.colorScheme.onSurface.withOpacity(0.05)),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
          child: Row(
            children: [
              Text(
                _isSameDay(_selectedDate, DateTime.now())
                    ? 'Today\'s Tasks & Events'
                    : '${DateFormat('MMM d').format(_selectedDate)} Tasks & Events',
                style: theme.textTheme.titleMedium
                    ?.copyWith(fontWeight: FontWeight.bold),
              ),
              if (dayItems.isNotEmpty) ...[
                const SizedBox(width: 8),
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                  decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${dayItems.length}',
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 12,
                        fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ],
          ),
        ),
        Expanded(
          child: RefreshIndicator(
            onRefresh: _refresh,
            child: dayItems.isEmpty
                ? ListView(
                    physics: const AlwaysScrollableScrollPhysics(),
                    children: [
                      SizedBox(
                        height: MediaQuery.of(context).size.height * 0.25,
                        child: Center(
                          child: Text(
                            'No events or tasks for this day',
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.onSurface
                                  .withOpacity(0.5),
                            ),
                          ),
                        ),
                      ),
                    ],
                  )
                : ListView.builder(
                    physics: const AlwaysScrollableScrollPhysics(),
                    padding: const EdgeInsets.symmetric(
                        horizontal: 24, vertical: 8),
                    itemCount: dayItems.length,
                    itemBuilder: (context, index) {
                      return _buildTimelineEvent(theme, dayItems[index]);
                    },
                  ),
          ),
        ),
      ],
    );
  }

  int _eventCountForDay(
    DateTime day,
    List<ScheduleEventModel> events,
    List<Map<String, dynamic>> tasks,
  ) {
    return _itemsForDate(events, tasks, day).length;
  }

  Widget _buildScrollableCalendar(
    ThemeData theme,
    List<ScheduleEventModel> events,
    List<Map<String, dynamic>> tasks,
  ) {
    final weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                '${_monthName(_selectedDate.month)} ${_selectedDate.year}',
                style: theme.textTheme.titleMedium
                    ?.copyWith(fontWeight: FontWeight.bold),
              ),
              Row(
                children: [
                  GestureDetector(
                    onTap: () => setState(() {
                      _selectedDate = DateTime(
                        _selectedDate.month == 1
                            ? _selectedDate.year - 1
                            : _selectedDate.year,
                        _selectedDate.month == 1
                            ? 12
                            : _selectedDate.month - 1,
                        _selectedDate.day,
                      );
                    }),
                    child: Container(
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        color: theme.colorScheme.surface,
                        shape: BoxShape.circle,
                        border: Border.all(
                            color:
                                theme.colorScheme.onSurface.withOpacity(0.1)),
                      ),
                      child: Icon(Icons.chevron_left,
                          size: 18, color: theme.colorScheme.onSurface),
                    ),
                  ),
                  const SizedBox(width: 8),
                  GestureDetector(
                    onTap: () => setState(() {
                      _selectedDate = DateTime(
                        _selectedDate.month == 12
                            ? _selectedDate.year + 1
                            : _selectedDate.year,
                        _selectedDate.month == 12
                            ? 1
                            : _selectedDate.month + 1,
                        _selectedDate.day,
                      );
                    }),
                    child: Container(
                      width: 32,
                      height: 32,
                      decoration: BoxDecoration(
                        color: theme.colorScheme.surface,
                        shape: BoxShape.circle,
                        border: Border.all(
                            color:
                                theme.colorScheme.onSurface.withOpacity(0.1)),
                      ),
                      child: Icon(Icons.chevron_right,
                          size: 18, color: theme.colorScheme.onSurface),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
        SizedBox(
          height: 80,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 16),
            itemCount: 31,
            itemBuilder: (context, index) {
              final day = DateTime(_selectedDate.year, _selectedDate.month, 1)
                  .add(Duration(days: index));
              if (day.month != _selectedDate.month) {
                return const SizedBox.shrink();
              }
              final isSelected = day.day == _selectedDate.day;
              final count = _eventCountForDay(day, events, tasks);

              return GestureDetector(
                onTap: () => setState(() => _selectedDate = day),
                child: Container(
                  width: 50,
                  margin: const EdgeInsets.only(right: 8),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        weekDays[day.weekday - 1],
                        style: theme.textTheme.labelMedium?.copyWith(
                          color: isSelected
                              ? theme.colorScheme.primary
                              : theme.colorScheme.onSurface.withOpacity(0.5),
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Stack(
                        clipBehavior: Clip.none,
                        children: [
                          Container(
                            width: 40,
                            height: 40,
                            alignment: Alignment.center,
                            decoration: BoxDecoration(
                              color: isSelected
                                  ? theme.colorScheme.primary
                                  : Colors.transparent,
                              shape: BoxShape.circle,
                            ),
                            child: Text(
                              '${day.day}',
                              style: theme.textTheme.bodyMedium?.copyWith(
                                color: isSelected
                                    ? Colors.white
                                    : theme.colorScheme.onSurface,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                          if (count > 0)
                            Positioned(
                              right: -2,
                              top: -2,
                              child: Container(
                                width: 8,
                                height: 8,
                                decoration: const BoxDecoration(
                                  color: Colors.red,
                                  shape: BoxShape.circle,
                                ),
                              ),
                            ),
                        ],
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }

  String _monthName(int month) {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December'
    ];
    return months[month - 1];
  }

  Widget _buildTimelineEvent(ThemeData theme, _ScheduleDisplayItem item) {
    final startLabel = DateFormat('hh:mm a').format(item.startTime);
    final parts = startLabel.split(' ');

    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          SizedBox(
            width: 60,
            child: Column(
              children: [
                Text(
                  parts.first,
                  style: theme.textTheme.titleMedium
                      ?.copyWith(fontWeight: FontWeight.w500),
                ),
                if (parts.length > 1)
                  Text(
                    parts.last,
                    style: theme.textTheme.labelMedium?.copyWith(
                      color: theme.colorScheme.onSurface.withOpacity(0.6),
                      fontWeight: FontWeight.bold,
                    ),
                  ),
              ],
            ),
          ),
          Expanded(
            child: Container(
              margin: const EdgeInsets.only(bottom: 24),
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: theme.colorScheme.surface,
                borderRadius: BorderRadius.circular(24),
                border: Border.all(
                    color: theme.colorScheme.onSurface.withOpacity(0.05)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Flexible(
                        child: Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.all(6),
                              decoration: BoxDecoration(
                                color: _tintForType(item.type)
                                    .withOpacity(0.3),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Icon(
                                item.isTask
                                    ? Icons.task_alt
                                    : _iconForType(item.type),
                                color: theme.colorScheme.primary,
                                size: 20,
                              ),
                            ),
                            const SizedBox(width: 10),
                            Flexible(
                              child: Text(
                                item.title,
                                style: theme.textTheme.titleMedium
                                    ?.copyWith(fontWeight: FontWeight.bold),
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 8),
                      Text(
                        item.timeRange,
                        style: theme.textTheme.labelSmall?.copyWith(
                          fontWeight: FontWeight.bold,
                          color:
                              theme.colorScheme.onSurface.withOpacity(0.6),
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                  if (item.projectName != null) ...[
                    const SizedBox(height: 8),
                    Text(
                      item.projectName!,
                      style: theme.textTheme.labelSmall?.copyWith(
                        color: theme.colorScheme.primary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                  if (item.description != null &&
                      item.description!.isNotEmpty) ...[
                    const SizedBox(height: 12),
                    Text(
                      item.description!,
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.onSurface.withOpacity(0.7),
                        height: 1.5,
                      ),
                      maxLines: 3,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ],
                  if (item.isTask) ...[
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 8, vertical: 3),
                          decoration: BoxDecoration(
                            color: Colors.red.withOpacity(0.12),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: const Text(
                            'TASK',
                            style: TextStyle(
                              fontSize: 10,
                              fontWeight: FontWeight.bold,
                              color: Colors.red,
                            ),
                          ),
                        ),
                        if (item.taskStatus != null) ...[
                          const SizedBox(width: 8),
                          Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 8, vertical: 3),
                            decoration: BoxDecoration(
                              color: theme.colorScheme.primary
                                  .withOpacity(0.12),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Text(
                              item.taskStatus!
                                  .replaceAll('_', ' ')
                                  .toUpperCase(),
                              style: TextStyle(
                                fontSize: 10,
                                fontWeight: FontWeight.bold,
                                color: theme.colorScheme.primary,
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ],
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
