'use client';

import React, { useState, useEffect } from 'react';
import { 
  format, 
  addMonths, 
  subMonths, 
  startOfMonth, 
  endOfMonth, 
  startOfWeek, 
  endOfWeek, 
  eachDayOfInterval, 
  isSameMonth, 
  isSameDay, 
  isToday, 
  parseISO 
} from 'date-fns';
import { 
  ChevronLeft, 
  ChevronRight, 
  Plus, 
  Calendar as CalendarIcon, 
  Clock, 
  Video, 
  Phone, 
  AlertCircle, 
  FolderGit2,
  CheckCircle2,
  Trash2,
  Repeat
} from 'lucide-react';
import { ScheduleEventsApi, ProjectsApi, TasksApi, SubscriptionsApi } from '@/lib/api';

import { useProjectDrawer } from '@/context/ProjectDrawerContext';

interface ProjectScheduleProps {
  projectId: string;
}

export default function ProjectSchedule({ projectId: initialProjectId }: ProjectScheduleProps) {
  const { openProjectDrawer } = useProjectDrawer();
  const [selectedProjectId, setSelectedProjectId] = useState<string>(initialProjectId);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [events, setEvents] = useState<any[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [projectTasks, setProjectTasks] = useState<any[]>([]);
  const [subscriptions, setSubscriptions] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedDay, setSelectedDay] = useState<Date | null>(null);
  const [viewEvent, setViewEvent] = useState<any | null>(null);

  // Form State
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    type: 'MEETING',
    startTime: '10:00',
    endTime: '11:00',
    projectId: initialProjectId === 'all' ? '' : initialProjectId,
    linkedTaskId: '',
  });

  useEffect(() => {
    ProjectsApi.getAll().then(setProjects).catch(console.error);
  }, []);

  useEffect(() => {
    loadEvents();
  }, [selectedProjectId, currentDate]);

  useEffect(() => {
    if (formData.projectId) {
      TasksApi.getTasks(formData.projectId)
        .then(setProjectTasks)
        .catch(console.error);
    }
  }, [formData.projectId]);

  const loadEvents = async () => {
    setIsLoading(true);
    try {
      const [eventsData, subsData] = await Promise.all([
        ScheduleEventsApi.getEvents(selectedProjectId),
        SubscriptionsApi.getUpcoming().catch(() => [])
      ]);
      setEvents(eventsData || []);
      setSubscriptions(subsData || []);
    } catch (e) {
      console.error('Failed to load schedule events:', e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreateEvent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedDay || !formData.projectId) return;

    try {
      const dayIso = format(selectedDay, 'yyyy-MM-dd');
      const startDateTime = `${dayIso}T${formData.startTime}:00`;
      const endDateTime = formData.endTime ? `${dayIso}T${formData.endTime}:00` : undefined;

      await ScheduleEventsApi.create({
        projectId: formData.projectId,
        title: formData.title,
        description: formData.description,
        type: formData.type,
        startTime: startDateTime,
        endTime: endDateTime,
        linkedTaskId: formData.linkedTaskId || undefined,
      });

      setIsModalOpen(false);
      setFormData({
        title: '',
        description: '',
        type: 'MEETING',
        startTime: '10:00',
        endTime: '11:00',
        projectId: selectedProjectId === 'all' ? '' : selectedProjectId,
        linkedTaskId: '',
      });
      loadEvents();
    } catch (e) {
      console.error('Failed to create schedule event:', e);
    }
  };

  const handleDeleteEvent = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm('Are you sure you want to delete this event?')) return;
    try {
      await ScheduleEventsApi.delete(id);
      if (viewEvent?.id === id) setViewEvent(null);
      loadEvents();
    } catch (e) {
      console.error(e);
    }
  };

  const nextMonth = () => setCurrentDate(addMonths(currentDate, 1));
  const prevMonth = () => setCurrentDate(subMonths(currentDate, 1));
  const goToToday = () => setCurrentDate(new Date());

  const monthStart = startOfMonth(currentDate);
  const monthEnd = endOfMonth(monthStart);
  const startDate = startOfWeek(monthStart);
  const endDate = endOfWeek(monthEnd);

  const days = eachDayOfInterval({ start: startDate, end: endDate });

  const getDayEvents = (day: Date) => {
    const dayEvs = events.filter(event => {
      if (!event.startTime) return false;
      const eventDate = parseISO(event.startTime);
      return isSameDay(eventDate, day);
    });

    const dayTasks = projectTasks.filter(task => {
      if (!task.dueDate) return false;
      const taskDate = parseISO(task.dueDate);
      return isSameDay(taskDate, day);
    }).map(t => ({
      id: t.id,
      title: `Task: ${t.title}`,
      type: 'DEADLINE',
      startTime: t.dueDate,
      autoGenerated: true,
      description: t.description,
      project: t.project
    }));

    return [...dayEvs, ...dayTasks];
  };

  const getTypeStyles = (type: string, autoGenerated?: boolean) => {
    if (autoGenerated || type === 'DEADLINE') {
      return 'bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-900/30 dark:text-rose-300 dark:border-rose-800';
    }
    switch (type) {
      case 'MEETING':
        return 'bg-indigo-50 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-300 dark:border-indigo-800';
      case 'CALL':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800';
      case 'DELIVERABLE':
        return 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800';
      default:
        return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-white dark:bg-slate-900 relative">
      
      {/* Schedule Toolbar */}
      <div className="flex flex-col sm:flex-row items-center justify-between px-6 py-4 border-b border-gray-100 dark:border-slate-800 bg-white dark:bg-slate-900 gap-4 shrink-0">
        <div className="flex items-center gap-4">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white">
            {format(currentDate, 'MMMM yyyy')}
          </h2>

          <div className="flex items-center gap-1 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded-lg p-0.5">
            <button onClick={prevMonth} className="p-1 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-white dark:hover:bg-slate-700 rounded-md transition-colors">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button onClick={goToToday} className="px-2.5 py-1 text-xs font-bold text-gray-700 dark:text-gray-300 hover:bg-white dark:hover:bg-slate-700 rounded-md transition-colors">
              Today
            </button>
            <button onClick={nextMonth} className="p-1 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-white dark:hover:bg-slate-700 rounded-md transition-colors">
              ChevronRight <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Project Filter Dropdown */}
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <FolderGit2 className="w-4 h-4 text-gray-400" />
            <select
              value={selectedProjectId}
              onChange={(e) => setSelectedProjectId(e.target.value)}
              className="text-xs font-semibold text-gray-800 bg-gray-50 border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#0C3B2E]"
            >
              <option value="all">All Projects (Roll-up View)</option>
              {projects.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          </div>

          <button
            onClick={() => {
              setSelectedDay(new Date());
              setFormData(prev => ({
                ...prev,
                projectId: selectedProjectId === 'all' ? (projects[0]?.id || '') : selectedProjectId
              }));
              setIsModalOpen(true);
            }}
            className="flex items-center gap-2 bg-[#FFBA00] text-gray-900 px-4 py-2 rounded-lg text-xs font-bold hover:bg-[#E6A700] transition-colors border border-transparent shrink-0"
          >
            <Plus className="w-4 h-4" /> Add Event
          </button>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Main Calendar Area */}
        <div className="flex-1 overflow-auto p-6 bg-gray-50/30 dark:bg-slate-900 flex flex-col">
          <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 shadow-xs overflow-hidden flex-1 flex flex-col">
            
            {/* Day Headers */}
            <div className="grid grid-cols-7 border-b border-gray-200 dark:border-slate-700 bg-gray-50/80 dark:bg-slate-800/80 text-center font-bold text-xs text-gray-500 dark:text-gray-400 py-3">
            <div>Sun</div>
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thu</div>
            <div>Fri</div>
            <div>Sat</div>
          </div>

          {/* Days Cells */}
          <div className="grid grid-cols-7 auto-rows-fr divide-x divide-y divide-gray-100 dark:divide-slate-700 flex-1 min-h-[500px]">
            {days.map((day, idx) => {
              const dayEvents = getDayEvents(day);
              const isCurrentMonth = isSameMonth(day, currentDate);
              const isSelectedToday = isToday(day);

              return (
                <div
                  key={idx}
                  onClick={() => {
                    setSelectedDay(day);
                    setFormData(prev => ({
                      ...prev,
                      projectId: selectedProjectId === 'all' ? (projects[0]?.id || '') : selectedProjectId
                    }));
                    setIsModalOpen(true);
                  }}
                  className={`p-2 min-h-[100px] flex flex-col hover:bg-gray-50/80 dark:hover:bg-slate-700/50 cursor-pointer transition-colors ${
                    !isCurrentMonth ? 'bg-gray-50/40 dark:bg-slate-800/40 text-gray-300 dark:text-slate-600' : 'text-gray-900 dark:text-slate-200'
                  }`}
                >
                  <div className="flex justify-between items-center mb-1">
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${
                      isSelectedToday ? 'bg-[#0C3B2E] text-white' : 'text-gray-700'
                    }`}>
                      {format(day, 'd')}
                    </span>
                  </div>

                  {/* Day Events */}
                  <div className="space-y-1 overflow-y-auto max-h-[80px]">
                    {dayEvents.map((ev) => (
                      <div
                        key={ev.id}
                        onClick={(e) => {
                          e.stopPropagation();
                          setViewEvent(ev);
                        }}
                        className={`p-1.5 rounded-md border text-[11px] font-bold leading-tight truncate flex items-center justify-between gap-1 ${getTypeStyles(ev.type, ev.autoGenerated)}`}
                      >
                        <span className="truncate">{ev.title}</span>
                        {selectedProjectId === 'all' && ev.project?.name && (
                          <span className="text-[9px] opacity-75 font-semibold shrink-0">
                            ({ev.project.name})
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Right Sidebar */}
      <div className="w-80 shrink-0 border-l border-gray-200 dark:border-slate-800 bg-gray-50/50 dark:bg-slate-800/50 overflow-y-auto p-4 hidden xl:block">
        <h3 className="text-sm font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
          <Repeat className="w-4 h-4 text-[#0C3B2E] dark:text-[#6D9773]" /> Upcoming Subscriptions
        </h3>
        <div className="space-y-3 mb-8">
          {subscriptions.length === 0 ? (
            <div className="text-xs text-gray-500 dark:text-slate-400">No upcoming subscriptions.</div>
          ) : (
            subscriptions.slice(0, 5).map(sub => (
              <div key={sub.id} className="bg-white dark:bg-slate-800 p-3 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm">
                <div className="font-bold text-gray-900 dark:text-white text-xs mb-1 truncate">{sub.name}</div>
                <div className="flex justify-between items-center text-[10px] text-gray-500 dark:text-slate-400">
                  <span>{sub.frequency}</span>
                  <span className="font-semibold">{format(new Date(sub.nextBillingDate), 'MMM d, yyyy')}</span>
                </div>
              </div>
            ))
          )}
        </div>

        <h3 className="text-sm font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
          <CalendarIcon className="w-4 h-4 text-[#FFBA00]" /> Upcoming Activities
        </h3>
        <div className="space-y-3">
          {events.length === 0 ? (
            <div className="text-xs text-gray-500 dark:text-slate-400">No upcoming activities.</div>
          ) : (
            events
              .filter(e => e.startTime && new Date(e.startTime) >= new Date())
              .sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime())
              .slice(0, 5)
              .map(ev => (
                <div key={ev.id} className="bg-white dark:bg-slate-800 p-3 rounded-xl border border-gray-200 dark:border-slate-700 shadow-sm flex items-start gap-3">
                  <div className={`shrink-0 w-8 h-8 rounded-lg flex items-center justify-center ${getTypeStyles(ev.type, ev.autoGenerated)}`}>
                    <CalendarIcon className="w-4 h-4" />
                  </div>
                  <div className="min-w-0">
                    <div className="font-bold text-gray-900 dark:text-white text-xs truncate">{ev.title}</div>
                    <div className="text-[10px] text-gray-500 dark:text-slate-400 font-medium">
                      {format(new Date(ev.startTime), 'MMM d, h:mm a')}
                    </div>
                  </div>
                </div>
              ))
          )}
        </div>
      </div>

    </div>

    {/* Event Details Slide-over */}
      {viewEvent && (
        <div className="absolute inset-y-0 right-0 w-96 bg-white shadow-2xl border-l border-gray-200 z-50 p-6 flex flex-col justify-between animate-in slide-in-from-right duration-300">
          <div>
            <div className="flex justify-between items-center mb-4">
              <span className={`px-2.5 py-1 text-xs font-bold rounded-md border uppercase ${getTypeStyles(viewEvent.type, viewEvent.autoGenerated)}`}>
                {viewEvent.type} {viewEvent.autoGenerated ? '(Auto)' : ''}
              </span>
              <button onClick={() => setViewEvent(null)} className="text-gray-400 hover:text-gray-600">
                <Plus className="w-5 h-5 rotate-45" />
              </button>
            </div>

            <h3 className="text-lg font-bold text-gray-900 mb-2">{viewEvent.title}</h3>
            {viewEvent.project?.name && (
              <div className="text-xs font-bold text-[#0C3B2E] mb-4">
                <button
                  onClick={() => {
                    setViewEvent(null);
                    openProjectDrawer(viewEvent.project.id || viewEvent.projectId);
                  }}
                  className="flex items-center gap-1.5 hover:underline cursor-pointer"
                >
                  <FolderGit2 className="w-3.5 h-3.5" /> Project: {viewEvent.project.name}
                </button>
              </div>
            )}

            <div className="space-y-3 text-xs text-gray-600 mb-6 bg-gray-50 p-4 rounded-xl border border-gray-100">
              <div className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-gray-400" />
                <span className="font-semibold">{format(parseISO(viewEvent.startTime), 'PPPP')}</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-gray-400" />
                <span className="font-semibold">{format(parseISO(viewEvent.startTime), 'p')}</span>
              </div>
              {viewEvent.description && (
                <div className="pt-2 border-t border-gray-200/60 font-medium">
                  {viewEvent.description}
                </div>
              )}
            </div>
          </div>

          <div className="flex justify-end">
            <button
              onClick={(e) => handleDeleteEvent(viewEvent.id, e)}
              className="flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-700 font-bold rounded-lg text-xs hover:bg-rose-100 transition-colors"
            >
              <Trash2 className="w-4 h-4" /> Delete Event
            </button>
          </div>
        </div>
      )}

      {/* Add Event Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-xs z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-6 shadow-xl border border-gray-100">
            <div className="flex justify-between items-center mb-5">
              <h3 className="text-base font-bold text-gray-900">
                New Schedule Event {selectedDay && `(${format(selectedDay, 'MMM d')})`}
              </h3>
              <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-600">
                <Plus className="w-5 h-5 rotate-45" />
              </button>
            </div>

            <form onSubmit={handleCreateEvent} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">Project (Required)</label>
                <select
                  required
                  value={formData.projectId}
                  onChange={(e) => setFormData({ ...formData, projectId: e.target.value })}
                  className="w-full p-2.5 border border-gray-200 rounded-lg text-xs font-semibold focus:outline-none focus:border-[#0C3B2E]"
                >
                  <option value="">Select Project...</option>
                  {projects.map((p) => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">Event Title</label>
                <input
                  type="text"
                  required
                  placeholder="Meeting title or milestone..."
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="w-full p-2.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-[#0C3B2E]"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Event Type</label>
                  <select
                    value={formData.type}
                    onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-[#0C3B2E]"
                  >
                    <option value="MEETING">Meeting</option>
                    <option value="CALL">Call</option>
                    <option value="DEADLINE">Deadline</option>
                    <option value="DELIVERABLE">Deliverable</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Start Time</label>
                  <input
                    type="time"
                    value={formData.startTime}
                    onChange={(e) => setFormData({ ...formData, startTime: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-[#0C3B2E]"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-700 mb-1">Description</label>
                <textarea
                  rows={2}
                  placeholder="Optional details..."
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full p-2.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-[#0C3B2E]"
                />
              </div>

              {projectTasks.length > 0 && (
                <div>
                  <label className="block text-xs font-bold text-gray-700 mb-1">Link to Task (Optional)</label>
                  <select
                    value={formData.linkedTaskId}
                    onChange={(e) => setFormData({ ...formData, linkedTaskId: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:border-[#0C3B2E]"
                  >
                    <option value="">None</option>
                    {projectTasks.map((t) => (
                      <option key={t.id} value={t.id}>{t.title}</option>
                    ))}
                  </select>
                </div>
              )}

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 border border-gray-200 rounded-lg text-xs font-semibold text-gray-600 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-[#FFBA00] text-gray-900 font-bold rounded-lg text-xs hover:bg-[#E6A700] transition-colors"
                >
                  Save Event
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
