import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { ScheduleEventType } from '@prisma/client';
import { EventsGateway } from '../events/events.gateway';

@Injectable()
export class ScheduleEventsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly eventsGateway: EventsGateway
  ) {}

  private async getAccessibleProjectIds(currentUserId?: string): Promise<string[]> {
    if (!currentUserId) return [];

    const user = await this.prisma.user.findUnique({
      where: { id: currentUserId },
      select: { id: true, email: true, companyId: true, userType: true },
    });

    const clientContact = await this.prisma.clientContact.findFirst({
      where: { OR: [{ id: currentUserId }, { email: user?.email || currentUserId }] },
      select: { id: true, clientId: true, email: true },
    });

    const projectConditions: any[] = [];
    if (user?.userType !== 'CLIENT' && user?.companyId) {
      projectConditions.push({ client: { companyId: user.companyId } });
      projectConditions.push({ members: { some: { userId: user.id } } });
    }
    if (clientContact) {
      projectConditions.push({ clientId: clientContact.clientId });
      projectConditions.push({ client: { email: clientContact.email } });
      projectConditions.push({ members: { some: { clientContactId: clientContact.id } } });
      projectConditions.push({ members: { some: { user: { email: clientContact.email } } } });
    }
    if (user?.email) {
      if (user.userType === 'CLIENT' || !user.companyId) {
        projectConditions.push({ client: { email: user.email } });
        projectConditions.push({ client: { contacts: { some: { email: user.email } } } });
      }
      projectConditions.push({ members: { some: { user: { email: user.email } } } });
      projectConditions.push({ members: { some: { clientContact: { email: user.email } } } });
    }

    if (projectConditions.length === 0) return [];

    const allowedProjects = await this.prisma.project.findMany({
      where: { OR: projectConditions },
      select: { id: true },
    });

    return allowedProjects.map(p => p.id);
  }

  async getEvents(projectId?: string, currentUserId?: string) {
    const where: any = {};

    if (currentUserId) {
      const allowedIds = await this.getAccessibleProjectIds(currentUserId);
      if (projectId && projectId !== 'all') {
        if (!allowedIds.includes(projectId)) {
          return [];
        }
        where.projectId = projectId;
      } else {
        where.projectId = { in: allowedIds };
      }
    } else if (projectId && projectId !== 'all') {
      where.projectId = projectId;
    }

    return this.prisma.scheduleEvent.findMany({
      where,
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      },
      orderBy: { startTime: 'asc' }
    });
  }

  async createEvent(data: {
    projectId: string;
    title: string;
    description?: string;
    type?: ScheduleEventType;
    startTime: string | Date;
    endTime?: string | Date;
    linkedTaskId?: string;
    autoGenerated?: boolean;
    createdBy?: string;
  }) {
    const event = await this.prisma.scheduleEvent.create({
      data: {
        projectId: data.projectId,
        title: data.title,
        description: data.description,
        type: data.type || ScheduleEventType.MEETING,
        startTime: new Date(data.startTime),
        endTime: data.endTime ? new Date(data.endTime) : null,
        linkedTaskId: data.linkedTaskId || null,
        autoGenerated: data.autoGenerated ?? false,
        createdBy: data.createdBy || null,
      },
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      }
    });

    this.eventsGateway.broadcastToProject(data.projectId, 'schedule_event_created', event);
    return event;
  }

  async updateEvent(id: string, data: Partial<{
    title: string;
    description: string;
    type: ScheduleEventType;
    startTime: string | Date;
    endTime: string | Date;
    linkedTaskId: string;
  }>) {
    const existing = await this.prisma.scheduleEvent.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Schedule event not found');

    const updated = await this.prisma.scheduleEvent.update({
      where: { id },
      data: {
        ...(data.title !== undefined && { title: data.title }),
        ...(data.description !== undefined && { description: data.description }),
        ...(data.type !== undefined && { type: data.type }),
        ...(data.startTime !== undefined && { startTime: new Date(data.startTime) }),
        ...(data.endTime !== undefined && { endTime: data.endTime ? new Date(data.endTime) : null }),
        ...(data.linkedTaskId !== undefined && { linkedTaskId: data.linkedTaskId }),
      },
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      }
    });

    this.eventsGateway.broadcastToProject(updated.projectId, 'schedule_event_updated', updated);
    return updated;
  }

  async deleteEvent(id: string) {
    const existing = await this.prisma.scheduleEvent.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Schedule event not found');

    await this.prisma.scheduleEvent.delete({ where: { id } });
    this.eventsGateway.broadcastToProject(existing.projectId, 'schedule_event_deleted', { id, projectId: existing.projectId });
    return { success: true };
  }
}
