import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { ScheduleEventType } from '@prisma/client';
import { EventsGateway } from '../events/events.gateway';

@Injectable()
export class ScheduleEventsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly eventsGateway: EventsGateway
  ) {}

  async getEvents(projectId?: string) {
    const where: any = {};
    if (projectId && projectId !== 'all') {
      where.projectId = projectId;
    }

    return this.prisma.scheduleEvent.findMany({
      where,
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      },
      orderBy: { startTime: 'asc' }
    });
  }

  async createEvent(data: {
    projectId: string;
    title: string;
    description?: string;
    type?: ScheduleEventType;
    startTime: string | Date;
    endTime?: string | Date;
    linkedTaskId?: string;
    autoGenerated?: boolean;
    createdBy?: string;
  }) {
    const event = await this.prisma.scheduleEvent.create({
      data: {
        projectId: data.projectId,
        title: data.title,
        description: data.description,
        type: data.type || ScheduleEventType.MEETING,
        startTime: new Date(data.startTime),
        endTime: data.endTime ? new Date(data.endTime) : null,
        linkedTaskId: data.linkedTaskId || null,
        autoGenerated: data.autoGenerated ?? false,
        createdBy: data.createdBy || null,
      },
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      }
    });

    this.eventsGateway.broadcastToProject(data.projectId, 'schedule_event_created', event);
    return event;
  }

  async updateEvent(id: string, data: Partial<{
    title: string;
    description: string;
    type: ScheduleEventType;
    startTime: string | Date;
    endTime: string | Date;
    linkedTaskId: string;
  }>) {
    const existing = await this.prisma.scheduleEvent.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Schedule event not found');

    const updated = await this.prisma.scheduleEvent.update({
      where: { id },
      data: {
        ...(data.title !== undefined && { title: data.title }),
        ...(data.description !== undefined && { description: data.description }),
        ...(data.type !== undefined && { type: data.type }),
        ...(data.startTime !== undefined && { startTime: new Date(data.startTime) }),
        ...(data.endTime !== undefined && { endTime: data.endTime ? new Date(data.endTime) : null }),
        ...(data.linkedTaskId !== undefined && { linkedTaskId: data.linkedTaskId }),
      },
      include: {
        project: {
          select: { id: true, name: true }
        },
        linkedTask: {
          select: { id: true, title: true }
        }
      }
    });

    this.eventsGateway.broadcastToProject(updated.projectId, 'schedule_event_updated', updated);
    return updated;
  }

  async deleteEvent(id: string) {
    const existing = await this.prisma.scheduleEvent.findUnique({ where: { id } });
    if (!existing) throw new NotFoundException('Schedule event not found');

    await this.prisma.scheduleEvent.delete({ where: { id } });
    this.eventsGateway.broadcastToProject(existing.projectId, 'schedule_event_deleted', { id, projectId: existing.projectId });
    return { success: true };
  }
}
