class ScheduleEventModel {
  final String id;
  final String projectId;
  final String title;
  final String? description;
  final String type;
  final DateTime startTime;
  final DateTime? endTime;
  final String? linkedTaskId;
  final bool autoGenerated;
  final Map<String, dynamic>? project;
  final Map<String, dynamic>? linkedTask;

  ScheduleEventModel({
    required this.id,
    required this.projectId,
    required this.title,
    this.description,
    required this.type,
    required this.startTime,
    this.endTime,
    this.linkedTaskId,
    this.autoGenerated = false,
    this.project,
    this.linkedTask,
  });

  factory ScheduleEventModel.fromJson(Map<String, dynamic> json) {
    return ScheduleEventModel(
      id: json['id']?.toString() ?? '',
      projectId: json['projectId']?.toString() ?? '',
      title: json['title']?.toString() ?? 'Untitled',
      description: json['description']?.toString(),
      type: json['type']?.toString() ?? 'MEETING',
      startTime: DateTime.parse(json['startTime'].toString()).toLocal(),
      endTime: json['endTime'] != null
          ? DateTime.parse(json['endTime'].toString()).toLocal()
          : null,
      linkedTaskId: json['linkedTaskId']?.toString(),
      autoGenerated: json['autoGenerated'] == true,
      project: json['project'] as Map<String, dynamic>?,
      linkedTask: json['linkedTask'] as Map<String, dynamic>?,
    );
  }

  Map<String, dynamic> toCreateJson() {
    return {
      'projectId': projectId,
      'title': title,
      if (description != null && description!.isNotEmpty)
        'description': description,
      'type': type,
      'startTime': startTime.toUtc().toIso8601String(),
      if (endTime != null) 'endTime': endTime!.toUtc().toIso8601String(),
      if (linkedTaskId != null) 'linkedTaskId': linkedTaskId,
    };
  }

  Map<String, dynamic> toUpdateJson() {
    return {
      'title': title,
      if (description != null) 'description': description,
      'type': type,
      'startTime': startTime.toUtc().toIso8601String(),
      if (endTime != null) 'endTime': endTime!.toUtc().toIso8601String(),
      if (linkedTaskId != null) 'linkedTaskId': linkedTaskId,
    };
  }
}
